proxy:
  host: "localhost"
  port: 8080

auth:
  default_provider: "auth-service"
  
  providers:
    auth-service:
      type: "jwks"
      jwks_url: "http://localhost:5001/auth/jwks"
      refresh_interval: 1h
      issuer: "" # Optional but recommended

services:
  - url: "http://ima-warehouse-service.railway.internal:8080"
    alias: /warehouse
    auth:
      enabled: true
      provider: "" # uses default provider if empty